@email={{$dotenv CLOCKODO_EMAIL}}
@apiKey={{$dotenv CLOCKODO_API_KEY}}

### get all users
GET https://my.clockodo.com/api/v3/users?page=2
Accept: application/json
X-ClockodoApiUser: {{email}}
X-ClockodoApiKey: {{apiKey}}
X-Clockodo-External-Application: mcp-ts

### get my entries
# time_since=2023-02-28T12:00:00Z
GET https://my.clockodo.com/api/v2/entries?time_since=2025-09-01T00:00:00Z&time_until=2025-09-30T00:00:00Z&filter=%5B%7Busers_id:148226%7D%5D
Accept: application/json
X-ClockodoApiUser: {{email}}
X-ClockodoApiKey: {{apiKey}}
X-Clockodo-External-Application: mcp-ts

